### ISSUE TITLE
Metric should handle List values

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgpyo#10]
Would be nice to have Metric also handle round-tripping of List types.  Perhaps it could serialize out to `",".join(format(v) for v in value)` and parse it back on the way back in?

**Comment by samfulcrum** [comment]
@tfenne, during our 1:1 @nils pointed out that it appears `Metrics.format_value()` already handles list formats. In my example below  `Person.read()` returns two instances of `Person` both with List types. Let me know if this is not what you had in mind. 
```
import attr
from fgpyo.util.metric import Metric
from pathlib import Path
from typing import List

@attr.s(auto_attribs=True, frozen=True)
class Person(Metric["Person"]):
    name: List[str]
    age: List[int]

metrics = [
    Person(name=["Alice", "Sandy", "Max"], age=[40, 56, 39]),
    Person(name=["Bob"], age=[24])
]

Person.write(Path("metrics.txt"), *metrics)
print(list(Person.read(Path("metrics.txt"))))
# print message = 
#[Person(name=['Alice', 'Sandy', 'Max'], age=[40, 56, 39]), Person(name=['Bob'], age=[24])]
```

**Comment by nh13** [comment]
@samfulcrum what is the contents of `metrics.txt` so we can agree on the on-disk format?

**Comment by tfenne** [comment]
So I wrote a this test:

```python
@attr.s(frozen=True, auto_attribs=True)
class Fooey(Metric["Fooey"]):
    name: str
    int_list: List[int]
    str_list: List[str]


def test_list_format(tmp_path: Path) -> None:
    metrics = [
        Fooey(name="one_of_each", int_list=[7], str_list=["seven"]),
        Fooey(name="none_of_each", int_list=[], str_list=[]),
        Fooey(name="several_of_each", int_list=[1, 2, 3], str_list=["one", "two", "three"]),
    ]

    path = tmp_path / "fooey.txt"

    Fooey.write(path, *metrics)
    read_back = list(Fooey.read(path))

    assert read_back == metrics
```

And the file looks like (column aligning done after the fact for readability):

```
name            int_list  str_list
one_of_each     [7]       [seven]
none_of_each    []        []
several_of_each [1,2,3]   [one,two,three]
```

I think we want the on-disk format to not include the `[]`, would you agree @nh13?

**Comment by samfulcrum** [comment]
@tfenne If I am understanding correctly the existing code does handle lists, however on-disc format should omit square brackets?

**Comment by nh13** [comment]
Exactly, on disk format should not contain square brackets

**Comment by nh13** [comment]
@samfulcrum if the type is `List` then why should it be parsed as `None`?  Lets discuss offline.

**Comment by samfulcrum** [comment]
@nils per issue 9 empty strings are parsed back as None

**Comment by nh13** [comment]
Optional fields (not lists) should be parsed as none

**Comment by samfulcrum** [comment]
I have opened a PR for the branch `issue_10` https://github.com/fulcrumgenomics/fgpyo/pull/28.

**Comment by nh13** [comment]
@samfulcrum can this be closed?
