### ISSUE TITLE
Package code and tests should be organized in separate directories, to be more consistent with Python conventions

### ISSUE THREAD

**Issue by msto** [fulcrumgenomics/fgpyo#120]
It would be great if the structure of the project could be updated to be more consistent with Python packaging conventions (in before someone points out the oxymoron).

Tests should be packaged in a directory structure that mirrors the source directory tree, not bundled within the source:
```
fgpyo/
├── pyproject.toml
├── README.md
├── fgpyo/
│   └── module_1/
│       ├── __init__.py
│       └── foo.py
└── tests/
   └── module_1/
       ├── __init__.py
       └── test_foo.py
```
    
https://packaging.python.org/en/latest/tutorials/packaging-projects/
https://docs.python-guide.org/writing/structure/
https://py-pkgs.org/03-how-to-package-a-python#a-brief-introduction
https://kennethreitz.org/essays/2013/01/27/repository-structure-and-python

I think it'd be great to restructure `fgpyo` to be more consistent with convention and our Python template.

**Comment by nh13** [comment]
![image](https://github.com/fulcrumgenomics/fgpyo/assets/846274/689788d1-4257-4b58-ba7c-98573714c863)
