### ISSUE TITLE
Feature request: add __get_item__() to Cigar class

### ISSUE THREAD

**Issue by yfarjoun** [fulcrumgenomics/fgpyo#153]
This will enable users to access the i-th element of `cigar` with `cigar[i]` rather than `cigar.elements[i]`

**Comment by yfarjoun** [comment]
I dont' think so. currently it is frozen and uses a tuple which means that it's immutable. changing that seems like a much bigger change in the API.

**Comment by tfenne** [comment]
Agree that it should remain immutable ... and also like the idea of implementing `__get_item__()`.
