### ISSUE TITLE
`mkdocs` dependencies should be declared as a dependency group, not extras

### ISSUE THREAD

**Issue by msto** [fulcrumgenomics/fgpyo#165]
Per [past discussion](https://fulcrumgenomics.slack.com/archives/C04BQ9RMJ2G/p1718200843607199?thread_ts=1718200462.992179&cid=C04BQ9RMJ2G), I think it would make more sense to declare `mkdocs` and friends as a dependency group, rather than as extras. 

Extras are made available via pip's bracketed syntax (e.g. `pip install fgpyo[pysam]`) and imo should be limited to optional dependencies _for the end-user_.

Dependency groups are only available via `poetry install` (e.g. `poetry install --with docs`) and imo should be used for optional or required developer dependencies. (Required dependencies should be declared in the `dev` group, and optionals in other groups, as appropriate.)

For `mkdocs`, these dependencies could be declared in a `docs` group. However, if our `ci/check.sh` script requires `mkdocs build` to pass, I would suggest including these in the `dev` group.

**Comment by clintval** [comment]
+1

Extras are for extra package install dependencies for the end users, not build tools.
