### ISSUE TITLE
SamBuilder should support writing out to a path _without_ sorting.

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgpyo#20]
I need to emit query-grouped BAMs, so I'm doing this outside SamBuilder for now.  But would be nice if the `to_path()` method had a `sort: bool = True` parameter that could be turned off.  The header would then need to be edited to have `SO:unsorted` upon writing.

**Comment by clintval** [comment]
Closed with https://github.com/fulcrumgenomics/fgpyo/pull/25
