### ISSUE TITLE
sam.reader should support reading unmapped BAMs

### ISSUE THREAD

**Issue by nh13** [fulcrumgenomics/fgpyo#32]
Since unmapped BAMs do not have a sequence dictionary in their header, opening with `pysam` will fail.  So one has to instead use:

```python
        with AlignmentFile(str(in_bam), mode="rb", check_sq=False) as reader:
```

Can we add an `unmapped: bool = false` option to `sam.reader` and add it to the `kwargs` passed to `sam._pysam_open`?

**Comment by clintval** [comment]
Closed by: https://github.com/fulcrumgenomics/fgpyo/pull/37
