### ISSUE TITLE
Add a Metric.fast_concat() function to aggregate metrics across files

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgpyo#46]
Something like:

```
@staticmethod
def fast_concat(output: Path, inputs: *Path) -> None:
    pass
```

The idea would be _not_ to parse the files using `Metric.read()`, but instead largely just concatenate the files while:

1. Skipping the header line for all but the first file
2. Validating that the header lines are the same across all files

**Comment by TedBrookings** [comment]
Closed by https://github.com/fulcrumgenomics/fgpyo/pull/53
