### ISSUE TITLE
Make ProgressLogger a context manager

### ISSUE THREAD

**Issue by msto** [fulcrumgenomics/fgpyo#68]
(Note that it currently has an `__exit__()` method but not an `__enter__()` - are both required for a context manager?)

**Comment by TedBrookings** [comment]
ProgressLogger is derived from [AbstractContextManager](https://docs.python.org/3/library/contextlib.html#contextlib.AbstractContextManager) which contains default versions of those functions. It's actually [tested as a context manager](https://github.com/fulcrumgenomics/fgpyo/blob/ca4a572524d2e5f79838250603e2fcf4d5d63155/fgpyo/util/tests/test_logging.py#L31C6-L31C6).
