### ISSUE TITLE
Recent VCF work is not available in the public docs

### ISSUE THREAD

**Issue by clintval** [fulcrumgenomics/fgpyo#72]
I noticed Ted's recent PR:

- https://github.com/fulcrumgenomics/fgpyo/pull/47

Is missing from API docs:

- https://fgpyo.readthedocs.io/en/latest/

Probably an easy fix. It would be a separate issue but should we move to MkDoc?

**Comment by nh13** [comment]
Can be added quickly here: https://github.com/fulcrumgenomics/fgpyo/blob/main/docs/api.rst.  Then we can separately move to mkdocs.
