### ISSUE TITLE
Reconcile the CI helper script with GitHub Actions

### ISSUE THREAD

**Issue by clintval** [fulcrumgenomics/fgpyo#87]
Looks like isort isn't wired into GitHub Actions but is specified in a helper script here:

https://github.com/fulcrumgenomics/fgpyo/blob/0c5d6ffbbd3a539567dd385c32c245dbef368b03/ci/check.sh#L48

There are MyPy, Black, and isort plugins for pytest, so I think whoever tackles this should get the harness down to just:

```
poetry run pytest
```

And everything can be run underneath with that command.

**Comment by nh13** [comment]
I have a small preference for keeping each a separate step in github actions for easy feedback
