### ISSUE TITLE
Metric should handle Optional fields better

### ISSUE THREAD

**Issue by tfenne** [fulcrumgenomics/fgpyo#9]
Formatting of None should result in "", and formatting of Some(x) should result in formatting x.
And on the parsing side, need to set None if the value is empty, else parse the inner value.

**Comment by nh13** [comment]
@tfenne should we instead use the same "empty" token like we do in fgbio (`:none:`)?  See: https://github.com/fulcrumgenomics/fgbio/blob/f72a0c3271e4a147a4b0b66b83eeebf1671ab0f2/src/main/scala/com/fulcrumgenomics/util/Metric.scala#L134.  This delineates difference between a non-empty string, an empty-string, and no string.

**Comment by samfulcrum** [comment]
@nh13 just created the draft PR with unit tests we discussed https://github.com/fulcrumgenomics/fgpyo/pull/27

**Comment by samfulcrum** [comment]
Proposed solution in https://github.com/fulcrumgenomics/fgpyo/pull/29

**Comment by samfulcrum** [comment]
@tfenne @nh13 can we close this issue?

**Comment by nh13** [comment]
Not until #29 is approved by @tfenne and merged.

**Comment by samfulcrum** [comment]
@nh13 ah yes my bad I meant that comment for issue #10
