### ISSUE TITLE
Metric.write should support excluding attributes

### ISSUE THREAD

**Issue by msto** [fulcrumgenomics/fgpyo#90]
It is sometimes helpful to declare attributes on a `Metric` that are useful for internal logic, but would clutter the output.

Could we update `Metric.write` to accept a list of attribute names that will be excluded from the output?

**Comment by nh13** [comment]
One solution would be to override the `values` method when writing.

Another solution would be to have a parent class with _only_ the attributes written to file, and a sub-class that can have your internal attributes as well as the attributes from the parent class.  You then just need the writer to recognize the instances as the parent class.  You can do that by having a converter method (new instance of the parent), cast'ing, or something else.

I do think this is valuable regardless of the above alternative solutions, but how would data be read back in when those skipped fields are not stored?
